import enum
import uuid
from datetime import date
from decimal import Decimal

from sqlalchemy import (
    CheckConstraint,
    Date,
    Enum,
    ForeignKey,
    ForeignKeyConstraint,
    Index,
    Numeric,
    SmallInteger,
    String,
    Uuid,
    func,
    text,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base_class import Base, TimestampMixin
from app.models.category import Category, TransactionType, transaction_type_enum

# NUMERIC(12, 2): exact decimal, up to 99,99,99,99,999.99 - far beyond personal use.
MONEY = Numeric(12, 2)


class PaymentMethod(enum.StrEnum):
    CASH = "cash"
    UPI = "upi"
    CARD = "card"
    BANK = "bank"


payment_method_enum = Enum(
    PaymentMethod, name="payment_method", values_callable=lambda e: [m.value for m in e]
)

# Payment method describes how money was *spent*; income never carries one.
PAYMENT_METHOD_EXPENSE_ONLY = "type = 'expense' OR payment_method IS NULL"


class Transaction(TimestampMixin, Base):
    """A single expense or income entry.

    Expenses and income share one table because they share every column and are almost
    always read together (history, recent activity, monthly totals). `type` distinguishes
    them, and the composite foreign key below makes a mismatched category impossible.
    """

    __tablename__ = "transactions"
    __table_args__ = (
        CheckConstraint("amount > 0", name="amount_positive"),
        CheckConstraint(PAYMENT_METHOD_EXPENSE_ONLY, name="payment_method_expense_only"),
        ForeignKeyConstraint(
            ["category_id", "type"],
            ["categories.id", "categories.kind"],
            name="fk_transactions_category_kind",
        ),
        # Serves every hot query: per-user month ranges, newest-first listings and
        # keyset pagination on (occurred_on, created_at, id).
        Index("ix_transactions_user_date", "user_id", "occurred_on", "created_at", "id"),
        # Supports the FK and the per-category breakdown.
        Index("ix_transactions_category_id", "category_id"),
        # A recurring rule produces at most one transaction per date, even if two requests
        # race to generate the same occurrence.
        Index(
            "uq_transactions_recurring_occurrence",
            "recurring_rule_id",
            "occurred_on",
            unique=True,
            postgresql_where=text("recurring_rule_id IS NOT NULL"),
        ),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        Uuid, primary_key=True, default=uuid.uuid4, server_default=func.gen_random_uuid()
    )
    user_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("users.id", ondelete="CASCADE"), nullable=False
    )
    type: Mapped[TransactionType] = mapped_column(transaction_type_enum, nullable=False)
    amount: Mapped[Decimal] = mapped_column(MONEY, nullable=False)
    category_id: Mapped[int] = mapped_column(SmallInteger, nullable=False)
    description: Mapped[str] = mapped_column(
        String(200), nullable=False, default="", server_default=""
    )
    # A calendar date, not a timestamp: "23 September" must stay 23 September in every zone.
    occurred_on: Mapped[date] = mapped_column(Date, nullable=False)
    payment_method: Mapped[PaymentMethod | None] = mapped_column(payment_method_enum)
    # Set when generated by a recurring rule. Deleting the rule keeps its past transactions.
    recurring_rule_id: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey("recurring_rules.id", ondelete="SET NULL")
    )

    category: Mapped[Category] = relationship(lazy="joined")
